### ISSUE TITLE
[1.14.4] Please tag ores so they are compatible with crushers

### ISSUE THREAD

**Issue by ProsperCraft** [RayzoRayy/RaysDongles#10]
Your ores don't seem to be tagged so when you put them in a Silent's Crusher, or Useless ores crusher, they don't process like gold.  

I think this could be fixed by tagging them so they are considered the same as gold.

**Comment by RayzoRayy** [comment]
Thought I had them tagged. Maybe I did something wrong

**Comment by RayzoRayy** [comment]
So my ores are registered now with the tag system. However, I still think its not going to work because of how Silents crusher is. I think any mod dev of a mod with a crusher in it, needs to have some sort of config so you can set it up to where when you insert my ore into there machine, it doubles the output. I can't make it so if you put my topaz ore in silent's crusher, or any other crusher for that matter, you get 2 topaz out of it. I remember setting this up back in 1.12.2, and I had to configure Ender IO's machine in the configs to allow me to put my topaz ore into the machine and double the output. I'm pretty sure the mod devs now have to make it so the tag "topaz_ore" and all of the other gems, can be used with there mod's crusher. Hopefully that made sense, but all of my ores are properly registered with the tag system now.

**Comment by SilentChaos512** [comment]
Shouldn't the Nether ores be tagged the same as their vanilla counterparts? They produce the same output, so it makes sense to allow them to be used in the same recipes.

As for the gem ores, I can handle the recipes for those. Most of your gems overlap with one of my other mods anyway.

**Comment by RayzoRayy** [comment]
Oh yes you are right. For a minute I forgot about the Nether ores... long day. Thank you for that Chaos, I shall get an update out that tags those properly.

**Comment by RayzoRayy** [comment]
I have them tagged in the json format under Data/Forge/Tags/Blocks/Ores, is there anything else I need to do to make it work? Testing it, doesn't seem to work @SilentChaos512 
I'm not too familiar with the new tag system, so perhaps I did something wrong.

**Comment by RayzoRayy** [comment]
Oh nevermind, I think they need to be in the minecraft tags, not forge.

**Comment by RayzoRayy** [comment]
@ProsperCraft issue has been fixed. I didn't realized SilentChaos only had support for Iron and Gold for his crusher, so when I was testing my ores, I didn't test Iron and Gold, but now i've got it working with my nether ores Gold and Iron. When SilentChaos adds recipies for other ores, they'll automatically work in the future. :)
