### ISSUE TITLE
[Issue] Paxel from Ray's Dongles isn't acting as the correct tool for many mod items.

### ISSUE THREAD

**Issue by RZiegler979** [RayzoRayy/RaysDongles#18]
**Describe the bug**
When using a Rays Dongels paxel things like Exp Ore, Crafting Stations, etc... Don't react as if the tool is the correct type. Taking just as long to mine as if I wasn't using a tool at all. As a side note the paxels from mekanism work just fine on all the different mods items. This is what lead me to believe that these paxels aren't correctly registering as picks/axes when needed.

**To Reproduce**
Install Rays Dongles and Crafting stations or exp ore mods.
Place one in world and try to mine it.
Behaves as if mining by hand.

**Expected behavior**
Mines as if holding appropriate tool.

**Please complete the following information**
 Forge Version- 31.1.1
Minecraft Version- 1.15.2
Ray's Dongles Version- 4.2

**Please list all mod(s) AND version(s) here that you are currently using along side of my mod**
A lot, 130 mods. None that are interacting badly with Ray's Dongles, simply not registering as a pick/axe for all mods items. 

There are two possible issues I see here, either your tool isn't correctly set up as pick/axe or you don't support the other mods. I don't know how these tools are coded so I don't know if you need to add a line for every single item to mine it correctly or if there is just some generic code that handles pick/axe speed for unknown blocks. If the former(a new entry for every block) then I totally understand why you aren't supporting all the hundreds of mods out there. But if the problem is a simpler generic block fix, than this problem is yours. 

Thank You.

**Comment by RayzoRayy** [comment]
Hey there. So what's happening here is that in my mod, the paxel class has this line of code called Effective_ON. And what this does is it tells the paxels what it is going to be effective on( lol). Magerials wise it has everything listed in there, for vanilla( that I can recall). Paxels do not work on modded items because I cant list modded items in the effective on. My paxels have been needing a rewrite for a long time now, I just haven't had the time do something like this change yet to add supportfor modded blocks. When I have more time in the future, I would like to recode the paxels differently so they work on modded items and not just vanilla. I'm going to keep this issue open just so others can see it, and read so they know what's up if they read it and have the same problem. Thanks for your report though!:)

**Comment by RayzoRayy** [comment]
Fixed in 4.2.1, was actually eaiser than anticipated. Plus some new things. :D
