### ISSUE TITLE
Mass Mining Pick

### ISSUE THREAD

**Issue by Krissycat92** [RayzoRayy/RaysDongles#2]
Hello, I have both Slurpies Dongles and Veinminer installed on my version on minecraft (1.12.2)I have added the MassMining Pick to the whitelist for my veinminer but it still does not seem to work in veinmining anything.

**Comment by RayzoRayy** [comment]
Are you certain that you spelled the ID for the item correctly ? Im not sure how "whitelisting" works with veinminer as I always leave it default to veinmine with anything. If anything, it is an issue with veinminer, as veinminer normally works with the Mass Mining Pick, so im going to assume you spelled something wrong, or it is an issue with veinminer itsself, but I will see if I can recreate the issue.

**Comment by RayzoRayy** [comment]
So i've tried creating a test with veinminer. I can't get the whitelist feature to work, at all. If I remove all the pickaxes, and add mine, and a regular diamond pick from vanilla it does not work. So im not sure what the issue is, if im doing something wrong (I don't normally use veinminer) but it seems simple enough to understand, try creating an issue with portablejim and see if perhaps he can help you, maybe we are both doing something wrong, but I do not believe the issue to be with my pickaxe, since it works fine without a whitelist enabled. Also just to verify, the Id for mass mining pick is slurpiesdongles:vmpick. Hope you can get it figured out!

**Comment by Krissycat92** [comment]
HI! Thank you for getting back to me i actually figured out the issue, i
was uing the wrong tool id. I was looking on the wiki page and i couldn't
find the tool id anywhere so i was guessing it. thank you for all your help!

**Comment by RayzoRayy** [comment]
No worries! To find any ID just hold F3 and press H on your keyboard in Minecraft when your in a world, and then when you look at the item in JEI, itll tell you the ID for that item :). This works for any mod also, not just mine.

**Comment by Krissycat92** [comment]
Thank you so much, I was wracking my brain trying to find it. Thank you so
much!
