### ISSUE TITLE
[1.14.4] Hammers only break one block

### ISSUE THREAD

**Issue by kwpugh** [RayzoRayy/RaysDongles#5]
**Describe the bug**
I tried out most of the hammers and they only break one block, not 3x3

Using Forge 22 and v107 of the mod

**To Reproduce**
3. What happens '....'

**Expected behavior**

**Screenshots**

**Please complete the following information**
 Forge Version- 22
Minecraft Version- 1.14.4
Slurpie's Dongles Version(Please indicate exactly which version of my mod you are using)- 107

**Please list all mod(s) AND version(s) here that you are currently using along side of my mod**

**Additional context**

**Comment by RayzoRayy** [comment]
Works fine for me in Forge 28.0.14. Perhaps something in Forge broke again in a later version. Try Forge 28.0.14 and let me know if the hammers work in that forge version for you.

**Comment by RayzoRayy** [comment]
Hammers work fine for me in Forge 28.0.22 and above. Perhaps you have another mod conflicting, I know this was an issue below forge 28.0.14, but you shouldn't even be able to use my mod below Forge 28.0.14 since thats what it was built on. Going to close this issue as I don't have this bug, and you didn't include a modlist so I cant rule out potential mods that could cause the issue IF another mod is conflicting.
