### ISSUE TITLE
[1.14.4] Stacktrace in console- indexOutOfBoundsException: Index: 6, Size: 6

### ISSUE THREAD

**Issue by ProsperCraft** [RayzoRayy/RaysDongles#6]
**Describe the bug**
Players have been timing out every 5 mins or so for a couple hours while I was sleeping, so I checked on the logs and found this stacktrace.  It could be an interaction between the linked destruction mod not sure, warmroast said the server was crashed- Unsafe park-

Stacktrace-
https://gist.github.com/ProsperCraft/0226456d47d6fe95ab27e879b694a507

Logs-

[debug.log](https://github.com/RedBullSlurpie/SlurpiesDongles/files/3492724/debug.log)
[latest.log](https://github.com/RedBullSlurpie/SlurpiesDongles/files/3492725/latest.log)

**Please complete the following information**
 Forge Version- forge-1.14.4-28.0.45
Minecraft Version-  1.14.4
Slurpie's Dongles Version(Please indicate exactly which version of my mod you are using)- 
Slurpies Dongles-1.14.4-1.0.10b

Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk
Version- .48

![176c892bc34125422554f1643ce28c28](https://user-images.githubusercontent.com/4427684/62869510-400a8d00-bcd5-11e9-9a8b-bf00d99558e1.png)

**Comment by RayzoRayy** [comment]
Could be related to how I am spawning the crops dropping from grass, the server might not like it, but not positive. Are you able to try this, without the mod linked destruction and see if any issues arise ?

**Comment by RayzoRayy** [comment]
My only other assumption is that, if this isn't caused by another mod, then the server doesn't like how I am currently spawning the crops that you get from breaking grass. They are  spawned as entities as a temporarily fix until Forge implements the new PR for HarvestDrops again, this is the only way I think i can go about having crops drop from grass without any mod conflicts arising.

**Comment by ProsperCraft** [comment]
I removed linked destruction from the pack for now.

**Comment by RayzoRayy** [comment]
Was that what was causing the issue or you have yet to test it yet ?

**Comment by RayzoRayy** [comment]
Seems like its having an issue with the ArrayList from my mod. I'll look into this further with someone else and see what we can come up with. As a simple fix for now, you can remove my mod, or downgrade the version to 1.0.8 before this change was implemented

**Comment by RayzoRayy** [comment]
Hoping that Forge implements the PR for Harvest Drops soon so I can switch to using that, as this work around isin't a proper way of doing this. For now i'm going to leave this alone and hope that Forge releases the PR soon so I can switch to that, i'd rather not go back to the injecting method because than other mods can have incompatibility, but for now i'd use version 1.0.8 of my mod, it has a few bugs, but if you want to use my mod still, then i'd recommend that for now until Forge gets that PR out.

**Comment by RayzoRayy** [comment]
Fixed in 2.0.3
